# Generated by Django 5.2.2 on 2025-06-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_emailconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='code',
            field=models.SlugField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
