# Generated by Django 5.2.2 on 2025-06-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_emailconfirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfirmation',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
