# Generated by Django 5.2.2 on 2025-06-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_emailconfirmation_is_verified_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailConfirmation',
            new_name='AccountVerification',
        ),
    ]
