# Generated by Django 5.2.2 on 2025-06-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_emailconfirmation_accountverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountverification',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
